volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=${LANG}
      - WG_HOST=${WG_HOST}
      - PORT=${PORT}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - UI_TRAFFIC_STATS=${UI_TRAFFIC_STATS}
      - WG_ENABLE_ONE_TIME_LINKS=${WG_ENABLE_ONE_TIME_LINKS}
      - UI_ENABLE_SORT_CLIENTS=${UI_ENABLE_SORT_CLIENTS}

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
